create table if not exists task (

    id serial not null primary key,
    name varchar(255) NOT NULL,
    tier varchar(16) not null,
    info varchar(255) not null,
    lms boolean not null,
    type varchar(255) not null,
    category varchar(255) not null
);

--EASY
insert into task (name, tier, info, lms, type, category)
VALUES
('Get bolt racks from Barrows', 'EASY', 'To be added', False, 'BOSS', 'BARROWS'),
('Get a Mole claw + skin', 'EASY', 'To be added', False, 'BOSS', 'GIANT_MOLE'),
('Get 1 Unique from Wintertodt', 'EASY', 'To be added', False, 'BOSS', 'WINTERTODT'),
('Get 1 Unique from Wintertodt', 'EASY', 'To be added', False, 'BOSS', 'WINTERTODT'),
('Get 1 Unique from Wintertodt', 'EASY', 'To be added', False, 'BOSS', 'WINTERTODT'),
('Get 1 Unique from Wintertodt', 'EASY', 'To be added', False, 'BOSS', 'WINTERTODT'),
('Get 1 Unique from Wintertodt', 'EASY', 'To be added', False, 'BOSS', 'WINTERTODT'),
('Get 3 new uniques from beginner clues', 'EASY', 'To be added', False, 'CLUES', 'BEGINNER'),
('Get 3 new uniques from beginner clues', 'EASY', 'To be added', False, 'CLUES', 'BEGINNER'),
('Get 5 new uniques from easy clues', 'EASY', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'EASY', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'EASY', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'EASY', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'EASY', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'EASY', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from medium clues', 'EASY', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'EASY', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'EASY', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'EASY', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from hard clues', 'EASY', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'EASY', 'To be added', False, 'CLUE', 'HARD'),
('Get Runner boots', 'EASY', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get Penance gloves', 'EASY', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get a Granite body', 'EASY', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get 1 new halo', 'EASY', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get the full Red decorative set', 'EASY', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get the Zamorak hood & cloak', 'EASY', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get the Saradomin hood & cloak', 'EASY', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get 1 Angler piece', 'EASY', 'To be added', False, 'MINIGAME', 'FISHING_TRAWLER'),
('Get 1 Angler piece', 'EASY', 'To be added', False, 'MINIGAME', 'FISHING_TRAWLER'),
('Get 1 Angler piece', 'EASY', 'To be added', False, 'MINIGAME', 'FISHING_TRAWLER'),
('Get 1 Angler piece', 'EASY', 'To be added', False, 'MINIGAME', 'FISHING_TRAWLER'),
('Get 1 new unique from Gnome Restaurant', 'EASY', 'To be added', False, 'MINIGAME', 'GNOME_RESTAURANT'),
('Get a Beginner wand', 'EASY', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Unlock bones to peaches', 'EASY', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Get Infinity boots', 'EASY', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Get Infinity gloves', 'EASY', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Get a Void Knight seal', 'EASY', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get Void Knight gloves', 'EASY', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get a Void Knight mace', 'EASY', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get 1 piece of Rogue equipment', 'EASY', 'To be added', False, 'MINIGAME', 'ROGUES_DEN'),
('Get 1 piece of Rogue equipment', 'EASY', 'To be added', False, 'MINIGAME', 'ROGUES_DEN'),
('Get 1 unique from Shades of Mort''ton', 'EASY', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'EASY', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 piece of Lumberjack equipment', 'EASY', 'To be added', False, 'MINIGAME', 'TEMPLE_TREKKING'),
('Get the Gricoller''s can', 'EASY', 'To be added', False, 'MINIGAME', 'TITHE_FARM'),
('Get 1 piece of Farmer''s equipment', 'EASY', 'To be added', False, 'MINIGAME', 'TITHE_FARM'),
('Get Blue Rum', 'EASY', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get Red Rum', 'EASY', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get The stuff', 'EASY', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Pearl fishing rod', 'EASY', 'To be added', False, 'OTHER', 'AREIAL_FISHING'),
('Get 1 unique Champion scroll', 'EASY', 'To be added', False, 'OTHER', 'CHAMPIONS_CHALLENGE'),
('Get the Marksman headpiece', 'EASY', 'To be added', False, 'OTHER', 'CHOMPY_BIRD_HUNTING'),
('Get a Tea flask', 'EASY', 'To be added', False, 'OTHER', 'CREATURE_CREATION'),
('Get a Rune satchel', 'EASY', 'To be added', False, 'OTHER', 'CREATURE_CREATION'),
('Get a Green satchel', 'EASY', 'To be added', False, 'OTHER', 'CREATURE_CREATION'),
('Get a Red satchel', 'EASY', 'To be added', False, 'OTHER', 'CREATURE_CREATION'),
('Get a Black satchel', 'EASY', 'To be added', False, 'OTHER', 'CREATURE_CREATION'),
('Get a Rune defender', 'EASY', 'To be added', False, 'OTHER', 'CYCLOPES'),
('Get 2 unique notes from Fossil Island', 'EASY', 'To be added', False, 'OTHER', 'FOSSIL_ISLAND_NOTES'),
('Get 2 unique notes from Fossil Island', 'EASY', 'To be added', False, 'OTHER', 'FOSSIL_ISLAND_NOTES'),
('Get 1 piece of Prospector equipment', 'EASY', 'To be added', False, 'OTHER', 'MOTHERLODE_MINE'),
('Get 1 piece of Prospector equipment', 'EASY', 'To be added', False, 'OTHER', 'MOTHERLODE_MINE'),
('Get 1 piece of Prospector equipment', 'EASY', 'To be added', False, 'OTHER', 'MOTHERLODE_MINE'),
('Get 1 piece of Prospector equipment', 'EASY', 'To be added', False, 'OTHER', 'MOTHERLODE_MINE'),
('Get 2 unique Ancient pages', 'EASY', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'EASY', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get Revenant ether', 'EASY', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 piece of Graceful equipment', 'EASY', 'To be added', False, 'OTHER', 'ROOFTOP_AGILITY'),
('Get 1 piece of Graceful equipment', 'EASY', 'To be added', False, 'OTHER', 'ROOFTOP_AGILITY'),
('Get 1 piece of Graceful equipment', 'EASY', 'To be added', False, 'OTHER', 'ROOFTOP_AGILITY'),
('Get a Crawling hand', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Cockatrice head', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Mogres', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Mogres', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Brine sabre', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Turoths', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Turoths', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Black mask', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get the next tier of metal boots', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get the next tier of metal boots', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get the next tier of metal boots', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get the next tier of metal boots', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get the next tier of metal boots', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Mystic hat (light)', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get Mystic gloves (light)', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get Mystic boots (light)', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Infernal Mages', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Infernal Mages', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get Mystic gloves (dark)', 'EASY', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique Tzhaar drop', 'EASY', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get 1 unique Tzhaar drop', 'EASY', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get a Big swordfish', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Big bass', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Long bone', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get an Ecumenical key', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dark totem piece / Ancient shard', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dark totem piece / Ancient shard', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dark totem piece / Ancient shard', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dark totem piece / Ancient shard', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get Mining gloves', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Right skull half', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Left skull half', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Top of sceptre', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Bottom of sceptre', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Mossy key', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Giant key', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Fresh crab claw & Fresh crab shell', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Xeric''s talisman (inert)', 'EASY', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Complete the Ardougne Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Desert Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Falador Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Fremennik Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Kandarin Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Karamja Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Kourend&Kebos Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Lumbridge&Draynor Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Morytania Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Varrock Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Western Provinces Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Wilderness Easy Diary', 'EASY', 'To be added', False, 'DIARY', 'DIARY'),
('Get a Supply crate from Mahogany Homes', 'EASY', 'To be added', False, 'MINIGAME', 'MAHOGANY_HOMES'),
('Get 1 unique from Tempoross', 'EASY', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get 1 unique from Tempoross', 'EASY', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get 1 unique from Tempoross', 'EASY', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get 1 unique from Tempoross', 'EASY', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get 5 unique items at Camdozaal', 'EASY', 'To be added', False, 'OTHER', 'CAMDOZAAL'),
('Get 5 unique items at Camdozaal', 'EASY', 'To be added', False, 'OTHER', 'CAMDOZAAL'),
('Get 1 unique from Guardians of the Rift', 'EASY', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'EASY', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'EASY', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'EASY', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Giants'' Foundry', 'EASY', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY'),
('Get 1 unique from Giants'' Foundry', 'EASY', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY'),
('Get 1 unique from Giants'' Foundry', 'EASY', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY'),
('Get 1 unique from Giants'' Foundry', 'EASY', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY');

-- MEDIUM
insert into task (name, tier, info, lms, type, category)
VALUES
('Get 1 unique from Barrows', 'MEDIUM', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'MEDIUM', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'MEDIUM', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'MEDIUM', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'MEDIUM', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Crazy Archeologist', 'MEDIUM', 'To be added', False, 'BOSS', 'CRAZY_ARCHAEOLOGIST'),
('Get 1 unique from Crazy Archeologist', 'MEDIUM', 'To be added', False, 'BOSS', 'CRAZY_ARCHAEOLOGIST'),
('Get 1 unique from Crazy Archeologist', 'MEDIUM', 'To be added', False, 'BOSS', 'CRAZY_ARCHAEOLOGIST'),
('Get a Fire cape', 'MEDIUM', 'To be added', False, 'BOSS', 'FIGHT_CAVES'),
('Get Granite dust', 'MEDIUM', 'To be added', False, 'BOSS', 'GROTESQUE_GUARDIANS'),
('Get a Hill giant club', 'MEDIUM', 'To be added', False, 'BOSS', 'OBOR'),
('Get 1 Unique from Wintertodt', 'MEDIUM', 'To be added', False, 'BOSS', 'WINTERTODT'),
('Get 1 Unique from Wintertodt', 'MEDIUM', 'To be added', False, 'BOSS', 'WINTERTODT'),
('Get 1 Unique from Wintertodt', 'MEDIUM', 'To be added', False, 'BOSS', 'WINTERTODT'),
('Get Zulrah''s scales', 'MEDIUM', 'To be added', False, 'BOSS', 'ZULRAH'),
('Get a Zul-andra teleport', 'MEDIUM', 'To be added', False, 'BOSS', 'ZULRAH'),
('Get 3 new uniques from beginner clues', 'MEDIUM', 'To be added', False, 'CLUE', 'BEGINNER'),
('Get 3 new uniques from beginner clues', 'MEDIUM', 'To be added', False, 'CLUE', 'BEGINNER'),
('Get 5 new uniques from easy clues', 'MEDIUM', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'MEDIUM', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'MEDIUM', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'MEDIUM', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'MEDIUM', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'MEDIUM', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from medium clues', 'MEDIUM', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'MEDIUM', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'MEDIUM', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'MEDIUM', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from hard clues', 'MEDIUM', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'MEDIUM', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'MEDIUM', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'MEDIUM', 'To be added', False, 'CLUE', 'HARD'),
('Get a Fighter hat', 'MEDIUM', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get a Healer hat', 'MEDIUM', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get a Runner hat', 'MEDIUM', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get a Ranger hat', 'MEDIUM', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get a Fighter torso', 'MEDIUM', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get a Granite helm', 'MEDIUM', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get 1 new halo', 'MEDIUM', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get the Decorative ranged set', 'MEDIUM', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get the Decorative magic set', 'MEDIUM', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get 1 new unique from Gnome Restaurant', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GNOME_RESTAURANT'),
('Get 1 new unique from Gnome Restaurant', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GNOME_RESTAURANT'),
('Upgrade the MTA wand once', 'MEDIUM', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Upgrade the MTA wand once', 'MEDIUM', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Upgrade the MTA wand once', 'MEDIUM', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Get an Infinity hat', 'MEDIUM', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Get a Mage''s book', 'MEDIUM', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Get a Void melee helm', 'MEDIUM', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get a Void magic helm', 'MEDIUM', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get a Void ranger helm', 'MEDIUM', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get a Void Knight top', 'MEDIUM', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get a Void Knight robe', 'MEDIUM', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get 1 piece of Rogue equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'ROGUES_DEN'),
('Get 1 piece of Rogue equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'ROGUES_DEN'),
('Get 1 piece of Rogue equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'ROGUES_DEN'),
('Get 1 unique from Shades of Mort''ton', 'MEDIUM', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'MEDIUM', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'MEDIUM', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 piece of Lumberjack equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TEMPLTE_TREKKING'),
('Get 1 piece of Lumberjack equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TEMPLTE_TREKKING'),
('Get 1 piece of Lumberjack equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TEMPLTE_TREKKING'),
('Get 1 piece of Farmer''s equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TITHE_FARM'),
('Get 1 piece of Farmer''s equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TITHE_FARM'),
('Get 1 piece of Farmer''s equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TITHE_FARM'),
('Get the Seed box', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TITHE_FARM'),
('Get 1 Naval set', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get 1 Naval set', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Cutthroat flag', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Guilded smile flag', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Pearl fly fishing rod', 'MEDIUM', 'To be added', False, 'OTHER', 'AERIAL_FISHING'),
('Get the Pearl barbarian rod', 'MEDIUM', 'To be added', False, 'OTHER', 'AERIAL_FISHING'),
('Get 1 unique Champion scroll', 'MEDIUM', 'To be added', False, 'OTHER', 'CHAMPIONS_CHALLENGE'),
('Get 1 unique Champion scroll', 'MEDIUM', 'To be added', False, 'OTHER', 'CHAMPIONS_CHALLENGE'),
('Get 1 unique Elder chaos robe piece', 'MEDIUM', 'To be added', False, 'OTHER', 'CHAOS_DRUIDS'),
('Get 1 unique Elder chaos robe piece', 'MEDIUM', 'To be added', False, 'OTHER', 'CHAOS_DRUIDS'),
('Get the Ogre forester headpiece', 'MEDIUM', 'To be added', False, 'OTHER', 'CHOMPY_BIRD_HUNTING'),
('Get a Gold satchel', 'MEDIUM', 'To be added', False, 'OTHER', 'CREATURE_CREATION'),
('Get a Plain satchel', 'MEDIUM', 'To be added', False, 'OTHER', 'CREATURE_CREATION'),
('Get a Dragon defender', 'MEDIUM', 'To be added', False, 'OTHER', 'CYCLOPES'),
('Get 2 unique notes from Fossil Island', 'MEDIUM', 'To be added', False, 'OTHER', 'FOSSIL_ISLAND_NOTES'),
('Get 2 unique notes from Fossil Island', 'MEDIUM', 'To be added', False, 'OTHER', 'FOSSIL_ISLAND_NOTES'),
('Get 2 unique notes from Fossil Island', 'MEDIUM', 'To be added', False, 'OTHER', 'FOSSIL_ISLAND_NOTES'),
('Get the Coal bag', 'MEDIUM', 'To be added', False, 'OTHER', 'MOTHERLODE_MINE'),
('Get the Gem bag', 'MEDIUM', 'To be added', False, 'OTHER', 'MOTHERLODE_MINE'),
('Get 2 unique Ancient pages', 'MEDIUM', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'MEDIUM', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'MEDIUM', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'MEDIUM', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'MEDIUM', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'MEDIUM', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 1 piece of Graceful equipment', 'MEDIUM', 'To be added', False, 'OTHER', 'ROOFTOP_AGILITY'),
('Get 1 piece of Graceful equipment', 'MEDIUM', 'To be added', False, 'OTHER', 'ROOFTOP_AGILITY'),
('Get 1 piece of Graceful equipment', 'MEDIUM', 'To be added', False, 'OTHER', 'ROOFTOP_AGILITY'),
('Get tier 5 Shayzien armour', 'MEDIUM', 'To be added', False, 'OTHER', 'SHAYZIEN_ARMOUR'),
('Get a Basilisk head', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Gargoyles', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Gargoyles', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Kurasks', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Kurasks', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Granite longsword', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get Granite legs', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get the next tier of metal boots', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get the next tier of metal boots', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Mystic robe bottom (dark)', 'MEDIUM', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique Tzhaar drop', 'MEDIUM', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get 1 unique Tzhaar drop', 'MEDIUM', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get 1 unique Tzhaar drop', 'MEDIUM', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get 1 unique Tzhaar drop', 'MEDIUM', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get a Big shark', 'MEDIUM', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Curved bone', 'MEDIUM', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Shaman mask', 'MEDIUM', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get Superior mining gloves', 'MEDIUM', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Bracelet of ethereum or Rev cave teleport', 'MEDIUM', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get a Bracelet of ethereum or Rev cave teleport', 'MEDIUM', 'To be added', False, 'OTHER', 'REVENANTS'),
('Complete the Ardougne Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Desert Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Falador Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Fremennik Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Kandarin Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Karamja Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Kourend&Kebos Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Lumbridge&Draynor Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Morytania Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Varrock Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Western Provinces Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Wilderness Medium Diary', 'MEDIUM', 'To be added', False, 'DIARY', 'DIARY'),
('Get a Mask of Ranul', 'MEDIUM', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Giant egg sac(full)', 'MEDIUM', 'To be added', False, 'BOSS', 'SARACHNIS'),
('Get a Herb sack', 'MEDIUM', 'To be added', False, 'MINIGAME', 'TITHE_FARM'),
('Get a Plank sack', 'MEDIUM', 'To be added', False, 'MINIGAME', 'MAHOGANY_HOMES'),
('Get 1 piece of Carpenter equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'MAHOGANY_HOMES'),
('Get 1 piece of Carpenter equipment', 'MEDIUM', 'To be added', False, 'MINIGAME', 'MAHOGANY_HOMES'),
('Get an Ectoplasmator', 'MEDIUM', 'To be added', False, 'MINIGAME', 'SOUL_WARS'),
('Get a Penance skirt', 'MEDIUM', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Get a Ward upgrade kit', 'MEDIUM', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Granite clamp', 'MEDIUM', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Volcanic whip mix', 'MEDIUM', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Frozen whip mix', 'MEDIUM', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Steam staff upgrade kit', 'MEDIUM', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Lava staff upgrade kit', 'MEDIUM', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Dragon pickaxe upgrade kit', 'MEDIUM', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get an Ornate maul handle', 'MEDIUM', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Celestial ring', 'MEDIUM', 'To be added', False, 'OTHER', 'SHOOTING_STARS'),
('Get a Star fragment', 'MEDIUM', 'To be added', False, 'OTHER', 'SHOOTING_STARS'),
('Get 1 unique from Tempoross', 'MEDIUM', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get 1 unique from Tempoross', 'MEDIUM', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get 1 unique from Tempoross', 'MEDIUM', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get 1 unique from Tempoross', 'MEDIUM', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get 1 unique from Tempoross', 'MEDIUM', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get the Merfolk trident', 'MEDIUM', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique from Guardians of the Rift', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Giants'' Foundry', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY'),
('Get 1 unique from Giants'' Foundry', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY'),
('Get 1 unique from Giants'' Foundry', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY'),
('Get 1 unique from Giants'' Foundry', 'MEDIUM', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY');

-- HARD
insert into task (name, tier, info, lms, type, category)
VALUES
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'HARD', 'To be added', False, 'BOSS', 'BARROWS'),
('Get a unique from Unsired', 'HARD', 'To be added', False, 'BOSS', 'ABYSSAL_SIRE'),
('Get a unique from Unsired', 'HARD', 'To be added', False, 'BOSS', 'ABYSSAL_SIRE'),
('Get a unique from Unsired', 'HARD', 'To be added', False, 'BOSS', 'ABYSSAL_SIRE'),
('Get an Abyssal whip', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from the Chaos Elemental', 'HARD', 'To be added', False, 'BOSS', 'CHAOS_ELEMENTAL'),
('Get 1 unique from the Chaos Elemental', 'HARD', 'To be added', False, 'BOSS', 'CHAOS_ELEMENTAL'),
('Get 1 unique from Cerberus', 'HARD', 'To be added', False, 'BOSS', 'CERBERUS'),
('Get 1 unique from Cerberus', 'HARD', 'To be added', False, 'BOSS', 'CERBERUS'),
('Get 1 unique from Cerberus', 'HARD', 'To be added', False, 'BOSS', 'CERBERUS'),
('Get a unique shard 1', 'HARD', 'To be added', False, 'BOSS', 'CHAOS_FANATIC'),
('Get a unique shard 1', 'HARD', 'To be added', False, 'BOSS', 'CHAOS_FANATIC'),
('Get a new Boss pet', 'HARD', 'To be added', False, 'BOSS', 'PET'),
('Get 1 unique drop from Zamorak GWD', 'HARD', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from Zamorak GWD', 'HARD', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from Dagannoth Kings', 'HARD', 'To be added', False, 'BOSS', 'DAGANNOTH_KINGS'),
('Get 1 unique drop from Dagannoth Kings', 'HARD', 'To be added', False, 'BOSS', 'DAGANNOTH_KINGS'),
('Get 1 unique drop from Dagannoth Kings', 'HARD', 'To be added', False, 'BOSS', 'DAGANNOTH_KINGS'),
('Get 1 unique drop from Dagannoth Kings', 'HARD', 'To be added', False, 'BOSS', 'DAGANNOTH_KINGS'),
('Get 1 unique drop from Dagannoth Kings', 'HARD', 'To be added', False, 'BOSS', 'DAGANNOTH_KINGS'),
('Get 1 unique drop from Dagannoth Kings', 'HARD', 'To be added', False, 'BOSS', 'DAGANNOTH_KINGS'),
('Get 1 unique drop from Dagannoth Kings', 'HARD', 'To be added', False, 'BOSS', 'DAGANNOTH_KINGS'),
('Get 1 unique drop from Grotesque Guardians', 'HARD', 'To be added', False, 'BOSS', 'GROTESQUE_GUARDIANS'),
('Get 1 unique drop from Grotesque Guardians', 'HARD', 'To be added', False, 'BOSS', 'GROTESQUE_GUARDIANS'),
('Get 1 unique drop from Grotesque Guardians', 'HARD', 'To be added', False, 'BOSS', 'GROTESQUE_GUARDIANS'),
('Get 1 unique from the Kalphite Queen', 'HARD', 'To be added', False, 'BOSS', 'KALPHITE_QUEEN'),
('Get 1 unique from the Kalphite Queen', 'HARD', 'To be added', False, 'BOSS', 'KALPHITE_QUEEN'),
('Get Kbd heads', 'HARD', 'To be added', False, 'BOSS', 'KING_BLACK_DRAGON'),
('Get 1 unique drop from Kraken', 'HARD', 'To be added', False, 'BOSS', 'KRAKEN'),
('Get 1 unique drop from Kraken', 'HARD', 'To be added', False, 'BOSS', 'KRAKEN'),
('Get an Uncharged Trident', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a unique shard 3', 'HARD', 'To be added', False, 'BOSS', 'SCORPIA'),
('Get a unique shard 3', 'HARD', 'To be added', False, 'BOSS', 'SCORPIA'),
('Get Vorkath''s head', 'HARD', 'To be added', False, 'BOSS', 'VORKATH'),
('Get 1 unique from Zulrah', 'HARD', 'To be added', False, 'BOSS', 'ZULRAH'),
('Get 1 unique from Zulrah', 'HARD', 'To be added', False, 'BOSS', 'ZULRAH'),
('Get 1 unique from Zulrah', 'HARD', 'To be added', False, 'BOSS', 'ZULRAH'),
('Get 1 unique from Zulrah', 'HARD', 'To be added', False, 'BOSS', 'ZULRAH'),
('Get 3 new uniques from beginner clues', 'HARD', 'To be added', False, 'CLUE', 'BEGINNER'),
('Get 5 new uniques from easy clues', 'HARD', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'HARD', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'HARD', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'HARD', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'HARD', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from medium clues', 'HARD', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'HARD', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'HARD', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'HARD', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'HARD', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from hard clues', 'HARD', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'HARD', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'HARD', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'HARD', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'HARD', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'HARD', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'HARD', 'To be added', False, 'CLUE', 'HARD'),
('Get 2 new uniques from elite clues', 'HARD', 'To be added', False, 'CLUE', 'ELITE'),
('Get 2 new uniques from elite clues', 'HARD', 'To be added', False, 'CLUE', 'ELITE'),
('Get 2 new uniques from elite clues', 'HARD', 'To be added', False, 'CLUE', 'ELITE'),
('Get 2 new uniques from elite clues', 'HARD', 'To be added', False, 'CLUE', 'ELITE'),
('Get 2 new uniques from elite clues', 'HARD', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new halo', 'HARD', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get 1 new unique from Gnome Restaurant', 'HARD', 'To be added', False, 'MINIGAME', 'GNOME_RESTAURANT'),
('Get an Infinity top', 'HARD', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Get Infinity bottoms', 'HARD', 'To be added', False, 'MINIGAME', 'MAGE_TRAINING_ARENA'),
('Get 2 White decorative pieces', 'HARD', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get 2 White decorative pieces', 'HARD', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get 2 White decorative pieces', 'HARD', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get 2 White decorative pieces', 'HARD', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get an Elite void top', 'HARD', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get an Elite void robe', 'HARD', 'To be added', False, 'MINIGAME', 'PEST_CONTROL'),
('Get 1 Naval set', 'HARD', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get 1 Naval set', 'HARD', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get 1 Naval set', 'HARD', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Bronze fist flag', 'HARD', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Lucky shot flag', 'HARD', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get 1 unique Champion scroll', 'HARD', 'To be added', False, 'OTHER', 'CHAMPIONS_CHALLENGE'),
('Get 1 unique Champion scroll', 'HARD', 'To be added', False, 'OTHER', 'CHAMPIONS_CHALLENGE'),
('Get 1 unique Champion scroll', 'HARD', 'To be added', False, 'OTHER', 'CHAMPIONS_CHALLENGE'),
('Get 1 unique Elder chaos robe piece', 'HARD', 'To be added', False, 'OTHER', 'CHAOS_DRUIDS'),
('Get the Ogre expert headpiece', 'HARD', 'To be added', False, 'OTHER', 'CHOMPY_BIRD_HUNTING'),
('Get a unique from Demonic gorillas', 'HARD', 'To be added', False, 'OTHER', 'GLOUGHS_EXPERIMENTS'),
('Get a unique from Demonic gorillas', 'HARD', 'To be added', False, 'OTHER', 'GLOUGHS_EXPERIMENTS'),
('Get a unique from Demonic gorillas', 'HARD', 'To be added', False, 'OTHER', 'GLOUGHS_EXPERIMENTS'),
('Get a unique from Demonic gorillas', 'HARD', 'To be added', False, 'OTHER', 'GLOUGHS_EXPERIMENTS'),
('Get 2 unique Ancient pages', 'HARD', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'HARD', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'HARD', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get a Kurask head', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get Dragon boots', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Dark bow', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Thermonuclear smoke devil', 'HARD', 'To be added', False, 'BOSS', 'THERMONUCLEAR_SMOKE_DEVIL'),
('Get 1 unique Obsidian armour drop', 'HARD', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get 1 unique Obsidian armour drop', 'HARD', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get a Dragon warhammer', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Pharaoh''s sceptre', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get Chewed bones', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Dragon spear', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get Expert mining gloves', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Complete the Ardougne Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Desert Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Falador Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Fremennik Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Kandarin Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Karamja Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Kourend&Kebos Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Lumbridge&Draynor Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Morytania Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Varrock Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Western Provinces Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Wilderness Hard Diary', 'HARD', 'To be added', False, 'DIARY', 'DIARY'),
('Get Bryophyta''s essence', 'HARD', 'To be added', False, 'BOSS', 'BRYOPHYTA'),
('Get a Sarachnis Cudgel', 'HARD', 'To be added', False, 'BOSS', 'SARACHNIS'),
('Get 1 unique from the Gauntlet', 'HARD', 'To be added', False, 'BOSS', 'GAUNTLET'),
('Get 1 unique from the Gauntlet', 'HARD', 'To be added', False, 'BOSS', 'GAUNTLET'),
('Get the Elven signet', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get an Enhanced crystal teleport seed', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get the Basilisk jaw', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a shield left half', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Pirate''s hook', 'HARD', 'To be added', False, 'MINIGAME', 'BRIMHAVEN_AGILITY_ARENA'),
('Get 2 uniques from the Hallowed Sepulchre', 'HARD', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get 2 uniques from the Hallowed Sepulchre', 'HARD', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get 2 uniques from the Hallowed Sepulchre', 'HARD', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get 2 uniques from the Hallowed Sepulchre', 'HARD', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get 2 uniques from the Hallowed Sepulchre', 'HARD', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get 2 uniques from the Hallowed Sepulchre', 'HARD', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Unlock 2 monkey backpack transformations', 'HARD', 'To be added', False, 'OTHER', 'MONKEY_BACKPACKS'),
('Unlock 2 monkey backpack transformations', 'HARD', 'To be added', False, 'OTHER', 'MONKEY_BACKPACKS'),
('Unlock 2 monkey backpack transformations', 'HARD', 'To be added', False, 'OTHER', 'MONKEY_BACKPACKS'),
('Get Amy''s saw', 'HARD', 'To be added', False, 'MINIGAME', 'MAHOGANY_HOMES'),
('Get 1 piece of Carpenter equipment', 'HARD', 'To be added', False, 'MINIGAME', 'MAHOGANY_HOMES'),
('Get 1 piece of Carpenter equipment', 'HARD', 'To be added', False, 'MINIGAME', 'MAHOGANY_HOMES'),
('Get a Blood shard', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Soul cape', 'HARD', 'To be added', False, 'MINIGAME', 'SOUL_WARS'),
('Get 1 unique from Shades of Mort''ton', 'HARD', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'HARD', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get a new dark bow paint from LMS', 'HARD', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a new dark bow paint from LMS', 'HARD', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a new dark bow paint from LMS', 'HARD', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a new dark bow paint from LMS', 'HARD', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Brimhaven graceful set recolour', 'HARD', 'To be added', False, 'MINIGAME', 'BRIMHAVEN_AGILITY_ARENA'),
('Get a Volcanic mine teleport', 'HARD', 'To be added', False, 'MINIGAME', 'VOLCANIC_MINE'),
('Get a Heat-proof vessel', 'HARD', 'To be added', False, 'MINIGAME', 'VOLCANIC_MINE'),
('Get 1 unique from Tempoross', 'HARD', 'To be added', False, 'BOSS', 'TEMPOROSS'),
('Get a Vial of blood (from Story mode ToB)', 'HARD', 'To be added', False, 'RAIDS', 'THEATRE_OF_BLOOD'),
('Get a unique Egg Sac from the Grubby Chest', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a unique Egg Sac from the Grubby Chest', 'HARD', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Nihil shard / Ceremonial robe piece', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique Nihil shard / Ceremonial robe piece', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique Nihil shard / Ceremonial robe piece', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique Nihil shard / Ceremonial robe piece', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique Nihil shard / Ceremonial robe piece', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique Nihil shard / Ceremonial robe piece', 'HARD', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from Guardians of the Rift', 'HARD', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'HARD', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'HARD', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'HARD', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get a Colossal blade', 'HARD', 'To be added', False, 'MINIGAME', 'GIANTS_FOUNDRY');

-- ELITE
insert into task (name, tier, info, lms, type, category)
VALUES
('Get 1 unique from Barrows', 'ELITE', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'ELITE', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'ELITE', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique from Barrows', 'ELITE', 'To be added', False, 'BOSS', 'BARROWS'),
('Get a unique from Unsired', 'ELITE', 'To be added', False, 'BOSS', 'BARROWS'),
('Get a unique from Unsired', 'ELITE', 'To be added', False, 'BOSS', 'BARROWS'),
('Get 1 unique item from Mount Karuulm', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique item from Mount Karuulm', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique crystal/stone from Cerberus', 'ELITE', 'To be added', False, 'BOSS', 'CERBERUS'),
('Get 1 unique crystal/stone from Cerberus', 'ELITE', 'To be added', False, 'BOSS', 'CERBERUS'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'ELITE', 'To be added', False, 'BOSS', 'GWD'),
('Get a Spirit shield or Holy elixir', 'ELITE', 'To be added', False, 'BOSS', 'CORPOREAL_BEAST'),
('Get a Spirit shield or Holy elixir', 'ELITE', 'To be added', False, 'BOSS', 'CORPOREAL_BEAST'),
('Get a Dark claw', 'ELITE', 'To be added', False, 'BOSS', 'SKOTIZO'),
('Get a new Boss pet', 'ELITE', 'To be added', False, 'BOSS', 'PET'),
('Get a new Boss pet', 'ELITE', 'To be added', False, 'BOSS', 'PET'),
('Get a new Boss pet', 'ELITE', 'To be added', False, 'BOSS', 'PET'),
('Get 1 unique from Thermonuclear smoke devil', 'ELITE', 'To be added', False, 'BOSS', 'THERMONUCLEAR_SMOKE_DEVIL'),
('Get 1 unique ring from Wilderness bosses', 'ELITE', 'To be added', False, 'BOSS', 'WILDERNESS'),
('Get 1 unique ring from Wilderness bosses', 'ELITE', 'To be added', False, 'BOSS', 'WILDERNESS'),
('Get 1 unique drop from Grotesque Guardians', 'ELITE', 'To be added', False, 'BOSS', 'GROTESQUE_GUARDIANS'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'ELITE', 'To be added', False, 'RAIDS', 'ANY'),
('Get 5 new uniques from easy clues', 'ELITE', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'ELITE', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'ELITE', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'ELITE', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from easy clues', 'ELITE', 'To be added', False, 'CLUE', 'EASY'),
('Get 5 new uniques from medium clues', 'ELITE', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'ELITE', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'ELITE', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'ELITE', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from medium clues', 'ELITE', 'To be added', False, 'CLUE', 'MEDIUM'),
('Get 5 new uniques from hard clues', 'ELITE', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'ELITE', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'ELITE', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'ELITE', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'ELITE', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'ELITE', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'ELITE', 'To be added', False, 'CLUE', 'HARD'),
('Get 5 new uniques from hard clues', 'ELITE', 'To be added', False, 'CLUE', 'HARD'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from elite clues', 'ELITE', 'To be added', False, 'CLUE', 'ELITE'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get 1 new unique from master clues', 'ELITE', 'To be added', False, 'CLUE', 'MASTER'),
('Get a Saradomin banner', 'ELITE', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get a Zamorak banner', 'ELITE', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get a Gold decorative helm', 'ELITE', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get a pair of Gold decorative boots', 'ELITE', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get 1 Naval set', 'ELITE', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get 1 Naval set', 'ELITE', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Treasure flag', 'ELITE', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Phasmatys flag', 'ELITE', 'To be added', False, 'MINIGAME', 'TROUBLE_BREWING'),
('Get the Chompy chick', 'ELITE', 'To be added', False, 'OTHER', 'CHOMPY_BIRD_HUNTING'),
('Get 1 unique Champion scroll', 'ELITE', 'To be added', False, 'OTHER', 'CHAMPIONS CHALLENGE'),
('Get 1 unique Champion scroll', 'ELITE', 'To be added', False, 'OTHER', 'CHAMPIONS CHALLENGE'),
('Get 1 unique Champion scroll', 'ELITE', 'To be added', False, 'OTHER', 'CHAMPIONS CHALLENGE'),
('Get 1 unique Champion scroll', 'ELITE', 'To be added', False, 'OTHER', 'CHAMPIONS CHALLENGE'),
('Upgrade to the (expert) dragon archer headpiece', 'ELITE', 'To be added', False, 'OTHER', 'CHOMPY_BIRD_HUNTING'),
('Upgrade to the (expert) dragon archer headpiece', 'ELITE', 'To be added', False, 'OTHER', 'CHOMPY_BIRD_HUNTING'),
('Get a unique from Demonic gorillas', 'ELITE', 'To be added', False, 'OTHER', 'GLOUGHS_EXPERIMENTS'),
('Get a unique from Demonic gorillas', 'ELITE', 'To be added', False, 'OTHER', 'GLOUGHS_EXPERIMENTS'),
('Get 2 unique Ancient pages', 'ELITE', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get 2 unique Ancient pages', 'ELITE', 'To be added', False, 'OTHER', 'MY_NOTES'),
('Get a Dust battlestaff', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Mist battlestaff', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique Obsidian armour drop', 'ELITE', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get a Toktz-mej-tal', 'ELITE', 'To be added', False, 'OTHER', 'TZHAAR'),
('Get dragon limbs', 'ELITE', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Complete the Ardougne Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Desert Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Falador Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Fremennik Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Kandarin Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Karamja Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Kourend&Kebos Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Lumbridge&Draynor Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Morytania Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Varrock Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Western Provinces Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Complete the Wilderness Elite Diary', 'ELITE', 'To be added', False, 'DIARY', 'DIARY'),
('Get the Crystal grail', 'ELITE', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get the Fish sack', 'ELITE', 'To be added', False, 'OTHER', 'AERIAL_FISHING'),
('Get 1 unique piece of the Dagon''hai robes', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique piece of the Dagon''hai robes', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from the Hallowed Sepulchre', 'ELITE', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get 1 unique from the Hallowed Sepulchre', 'ELITE', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get 1 unique from the Hallowed Sepulchre', 'ELITE', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get Granite boots', 'ELITE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get the Hosidius blueprints', 'ELITE', 'To be added', False, 'MINIGAME', 'MAHOGANY_HOMES'),
('Get 1 unique from Shades of Mort''ton', 'ELITE', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'ELITE', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'ELITE', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'ELITE', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'ELITE', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'ELITE', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get 1 unique from Shades of Mort''ton', 'ELITE', 'To be added', False, 'MINIGAME', 'SHADES_OF_MORTON'),
('Get a new Golden godsword special from LMS', 'ELITE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a new Golden godsword special from LMS', 'ELITE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a new Golden godsword special from LMS', 'ELITE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a new Golden godsword special from LMS', 'ELITE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Ash covered tome', 'ELITE', 'To be added', False, 'MINIGAME', 'VOLCANIC_MINE'),
('Get 1 unique from Revenants', 'ELITE', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'ELITE', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'ELITE', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'ELITE', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Guardians of the Rift', 'ELITE', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'ELITE', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'ELITE', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT'),
('Get 1 unique from Guardians of the Rift', 'ELITE', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT');

-- PETS
insert into task (name, tier, info, lms, type, category)
VALUES
('Abyssal orphan', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Baby mole', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Callisto cub', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Hellpuppy', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Ikkle hydra', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Jal-nib-rek/Tzrek-zuk', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Kalphite princess', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Lil'' zik', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Little nightmare', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Nexling', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Noon/Midnight', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Olmlet', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet chaos elemental', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet dagannoth prime', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet dagannoth rex', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet dagannoth supreme', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet dark core/corporeal critter', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet general graardor', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet k''ril tsutsaroth', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet kraken', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet kree''arra', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet smoke devil', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet snakeling', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Pet zilyana', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Prince black dragon', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Scorpia''s offspring', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Skotos', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Sraracha', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Tzrek-jad', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Venenatis spiderling', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Vet''ion jr', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Vorki', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Baby chinchompa', 'PETS', 'To be added', False, 'OTHER', 'SKILLING_PETS'),
('Beaver', 'PETS', 'To be added', False, 'OTHER', 'SKILLING_PETS'),
('Giant squirrel', 'PETS', 'To be added', False, 'OTHER', 'SKILLING_PETS'),
('Heron', 'PETS', 'To be added', False, 'OTHER', 'SKILLING_PETS'),
('Rift guardian', 'PETS', 'To be added', False, 'OTHER', 'SKILLING_PETS'),
('Rock golem', 'PETS', 'To be added', False, 'OTHER', 'SKILLING_PETS'),
('Rocky', 'PETS', 'To be added', False, 'OTHER', 'SKILLING_PETS'),
('Tangleroot', 'PETS', 'To be added', False, 'OTHER', 'SKILLING_PETS'),
('Bloodhound', 'PETS', 'To be added', False, 'CLUE', 'MASTER'),
('Chompy chick', 'PETS', 'To be added', False, 'OTHER', 'CHOMPY_BIRD_HUNTING'),
('Herbi', 'PETS', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Pet penance queen', 'PETS', 'To be added', False, 'MINIGAME', 'BARBARIAN_ASSAULT'),
('Phoenix', 'PETS', 'To be added', False, 'MINIGAME', 'WINTERTODT'),
('Youngllef', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Smolcano', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Tiny Tempor', 'PETS', 'To be added', False, 'BOSS', 'PET'),
('Lil'' creator', 'PETS', 'To be added', False, 'MINIGAME', 'SOUL_WARS'),
('Abyssal protector', 'PETS', 'To be added', False, 'MINIGAME', 'GUARDIANS_OF_THE_RIFT');

-- EXTRA
insert into task (name, tier, info, lms, type, category)
VALUES
('Get a Jar of chemicals', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of souls', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of sand', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of decay', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of swamp', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of eyes', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of stone', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of darkness', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of dreams', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of dirt', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of miasma', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of spirits', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get a Jar of smoke', 'EXTRA', 'To be added', False, 'BOSS', 'JAR'),
('Get 1 unique sigil from Corp', 'EXTRA', 'To be added', False, 'BOSS', 'CORPOREAL_BEAST'),
('Get 1 unique sigil from Corp', 'EXTRA', 'To be added', False, 'BOSS', 'CORPOREAL_BEAST'),
('Get 1 unique sigil from Corp', 'EXTRA', 'To be added', False, 'BOSS', 'CORPOREAL_BEAST'),
('Get an Infernal cape', 'EXTRA', 'To be added', False, 'BOSS', 'INFERNO'),
('Get a Skeletal visage', 'EXTRA', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Wyvern visage', 'EXTRA', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique ring from Wilderness bosses', 'EXTRA', 'To be added', False, 'BOSS', 'WILDERNESS'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Get 1 unique from Raids (CoX or ToB)', 'EXTRA', 'To be added', False, 'RAIDS', 'ANY'),
('Finish all shared clue rewards ', 'EXTRA', 'To be added', False, 'CLUE', 'ANY'),
('Finish all easy clue uniques', 'EXTRA', 'To be added', False, 'CLUE', 'EASY'),
('Finish all medium clue uniques', 'EXTRA', 'To be added', False, 'CLUE', 'MEDIUM'),
('Finish all hard clue uniques', 'EXTRA', 'To be added', False, 'CLUE', 'HARD'),
('Finish all elite clue uniques', 'EXTRA', 'To be added', False, 'CLUE', 'ELITE'),
('Finish all master clue uniques', 'EXTRA', 'To be added', False, 'CLUE', 'MASTER'),
('Finish all hard clue rare uniques', 'EXTRA', 'To be added', False, 'CLUE', 'HARD'),
('Finish all elite clue rare uniques', 'EXTRA', 'To be added', False, 'CLUE', 'ELITE'),
('Finish all master rare clue uniques', 'EXTRA', 'To be added', False, 'CLUE', 'MASTER'),
('Complete the Gold decorative set', 'EXTRA', 'To be added', False, 'MINIGAME', 'CASTLE_WARS'),
('Get 1 unique from Revenants', 'EXTRA', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'EXTRA', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'EXTRA', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'EXTRA', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'EXTRA', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'EXTRA', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get 1 unique from Revenants', 'EXTRA', 'To be added', False, 'OTHER', 'REVENANTS'),
('Get an Amulet of eternal glory', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dragonstone armour piece', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dragonstone armour piece', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dragonstone armour piece', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dragonstone armour piece', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique Dragonstone armour piece', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a full Dark totem drop from Skotizo', 'EXTRA', 'To be added', False, 'BOSS', 'SKOTIZO'),
('Get 1 unique piece of the Dagon''hai robes', 'EXTRA', 'To be added', False, 'OTHER', 'SLAYER'),
('Get 1 unique from the Zalcano', 'EXTRA', 'To be added', False, 'BOSS', 'ZALCANO'),
('Get 1 unique from The Nightmare', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get 1 unique from The Nightmare', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get 1 unique from The Nightmare', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get 1 unique from The Nightmare', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get 1 unique from The Nightmare', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get 1 unique from The Nightmare', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get 1 unique from The Nightmare', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get 1 unique from The Nightmare', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get 1 unique mutagen', 'EXTRA', 'To be added', False, 'BOSS', 'ZULRAH'),
('Get 1 unique mutagen', 'EXTRA', 'To be added', False, 'BOSS', 'ZULRAH'),
('Get an Imbued heart or Eternal gem', 'EXTRA', 'To be added', False, 'OTHER', 'SLAYER'),
('Get an Imbued heart or Eternal gem', 'EXTRA', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Dragon full helm', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Dragon metal lump', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get a Dragon metal slice', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique piece of the Evil chicken outfit', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique piece of the Evil chicken outfit', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique piece of the Evil chicken outfit', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique piece of the Evil chicken outfit', 'EXTRA', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get 1 unique from the Gauntlet', 'EXTRA', 'To be added', False, 'BOSS', 'GAUNTLET'),
('Get a Draconic visage', 'EXTRA', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Dragonbone necklace', 'EXTRA', 'To be added', False, 'BOSS', 'VORKATH'),
('Get the Deadman''s chest', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Deadman''s legs', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Deadman''s cape', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Swift blade', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get an Armadyl halo', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Bandos halo', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Seren halo', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get an Ancient halo', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Brassica halo', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Guthixian icon', 'EXTRA', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get a Slepey tablet', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get the Metamorphic dust', 'EXTRA', 'To be added', False, 'RAID', 'CHAMBERS_OF_XERIC'),
('Get the Sanguine dust', 'EXTRA', 'To be added', False, 'RAID', 'THEATRE_OF_BLOOD'),
('Get the Parasitic egg', 'EXTRA', 'To be added', False, 'BOSS', 'NIGHTMARE'),
('Get a Twisted ancestral colour kit', 'EXTRA', 'To be added', False, 'RAID', 'CHAMBERS_OF_XERIC'),
('Get a Holy ornament kit', 'EXTRA', 'To be added', False, 'RAID', 'THEATRE_OF_BLOOD'),
('Get a Sanguine ornament kit', 'EXTRA', 'To be added', False, 'RAID', 'THEATRE_OF_BLOOD'),
('Get 1 unique from the Zalcano', 'EXTRA', 'To be added', False, 'BOSS', 'ZALCANO'),
('Get 1 unique from the Hallowed Sepulchre', 'EXTRA', 'To be added', False, 'MINIGAME', 'HALLOWED_SEPULCHRE'),
('Get 1 unique drop from God Wars Dungeon', 'EXTRA', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'EXTRA', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'EXTRA', 'To be added', False, 'BOSS', 'GWD'),
('Get 1 unique drop from God Wars Dungeon', 'EXTRA', 'To be added', False, 'BOSS', 'GWD');

-- PASSIVE
insert into task (name, tier, info, lms, type, category)
VALUES
('Get the Golden tench', 'PASSIVE', 'To be added', False, 'OTHER', 'AERIAL_FISHING'),
('Get the Bottomless compost bucket', 'PASSIVE', 'To be added', False, 'BOSS', 'HESPORI'),
('Get the Stale Baguette', 'PASSIVE', 'To be added', False, 'OTHER', 'RANDOM_EVENTS'),
('Get a Hespori seed', 'PASSIVE', 'To be added', False, 'OTHER', 'MISCELLANEOUS'),
('Get an Iasor seed', 'PASSIVE', 'To be added', False, 'BOSS', 'HESPORI'),
('Get a Kronos seed', 'PASSIVE', 'To be added', False, 'BOSS', 'HESPORI'),
('Get an Attas seed', 'PASSIVE', 'To be added', False, 'BOSS', 'HESPORI'),
('Get all random event outfits', 'PASSIVE', 'To be added', False, 'OTHER', 'RANDOM_EVENTS'),
('Get a Broken dragon hasta', 'PASSIVE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Mystic hat (dusk)', 'PASSIVE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Mystic robe top (dusk)', 'PASSIVE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Mystic robe bottom (dusk)', 'PASSIVE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get Mystic gloves (dusk)', 'PASSIVE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get Mystic boots (dusk)', 'PASSIVE', 'To be added', False, 'OTHER', 'SLAYER'),
('Get a Godsword shard 1', 'PASSIVE', 'To be added', False, 'BOSS', 'GWD'),
('Get a Godsword shard 2', 'PASSIVE', 'To be added', False, 'BOSS', 'GWD'),
('Get a Godsword shard 3', 'PASSIVE', 'To be added', False, 'BOSS', 'GWD'),
('Get a Dark relic', 'PASSIVE', 'To be added', False, 'RAIDS', 'CHAMBERS_OF_XERIC'),
('Get a Torn prayer scroll', 'PASSIVE', 'To be added', False, 'RAIDS', 'CHAMBERS_OF_XERIC'),
('Get the Xeric''s guard', 'PASSIVE', 'To be added', False, 'RAIDS', 'CHAMBERS_OF_XERIC'),
('Get the Xeric''s warrior', 'PASSIVE', 'To be added', False, 'RAIDS', 'CHAMBERS_OF_XERIC'),
('Get the Xeric''s sentinel', 'PASSIVE', 'To be added', False, 'RAIDS', 'CHAMBERS_OF_XERIC'),
('Get the Xeric''s general', 'PASSIVE', 'To be added', False, 'RAIDS', 'CHAMBERS_OF_XERIC'),
('Get the Xeric''s champion', 'PASSIVE', 'To be added', False, 'RAIDS', 'CHAMBERS_OF_XERIC'),
('Get the Sinhaza shroud PASSIVE 1', 'PASSIVE', 'To be added', False, 'RAIDS', 'THEATRE_OF_BLOOD'),
('Get the Sinhaza shroud PASSIVE 2', 'PASSIVE', 'To be added', False, 'RAIDS', 'THEATRE_OF_BLOOD'),
('Get the Sinhaza shroud PASSIVE 3', 'PASSIVE', 'To be added', False, 'RAIDS', 'THEATRE_OF_BLOOD'),
('Get the Sinhaza shroud PASSIVE 4', 'PASSIVE', 'To be added', False, 'RAIDS', 'THEATRE_OF_BLOOD'),
('Get the Sinhaza shroud PASSIVE 5', 'PASSIVE', 'To be added', False, 'RAIDS', 'THEATRE_OF_BLOOD'),
('Get a cut Onyx from Tekton', 'PASSIVE', 'To be added', False, 'RAIDS', 'CHAMBERS_OF_XERIC'),
('Get the Gauntlet cape', 'PASSIVE', 'To be added', False, 'BOSS', 'GAUNTLET'),
('Get the Victor''s cape (1)', 'PASSIVE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Victor''s cape (10)', 'PASSIVE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Victor''s cape (50)', 'PASSIVE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Victor''s cape (100)', 'PASSIVE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Victor''s cape (500)', 'PASSIVE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING'),
('Get the Victor''s cape (1000)', 'PASSIVE', 'To be added', True, 'MINIGAME', 'LAST_MAN_STANDING');
